uint64 timestamp		# time since system start (microseconds)

uint32 device_id          	# unique device ID for the sensor that does not change between power cycles

float32 airspeed_m_s		# indicated airspeed in m/s
float32 flank_angle_rad		# flank angle at sensor location in radians
float32 angle_of_attack_rad	# angle of attack at sensor location in radians

float32 pitot_pressure_pa	# pitot probe stagnation pressure in Pascals
float32 static_pressure_pa	# pitot probe static pressure in Pascals

float32 pressure_alt_m		# pressure altitude in meters
