uint64 timestamp	# time since system start (microseconds)

float32 v_in_m_s		# relative velocity magnitude at sensor (m/s)
float32 direction_deg	# relative velocity direction at sensor in body x-y plane (deg)

float32 u_m_s		# relative velocity component at sensor in body x direction (m/s)
float32 v_m_s		# relative velocity component at sensor in body y direction (m/s)
float32 w_m_s		# relative velocity component at sensor in body z direction (m/s)

float32 t_c	# sensor temperature (deg Celcius)

# TOPICS sensor_anemometer
